apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abctech_deploy
  template:
    metadata:
      labels:
        app: abctech_deploy
    spec:
      containers:
      - name: abctech-container
        image: ravibhattinkw/abc_tech:18
        ports:
        - containerPort: 8090
      imagePullSecrets:
      - name: dockerhub-secret
